;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Test.StateTree.Event.Alert",DevComment="")
+GameplayTagList=(Tag="Test.StateTree.Event.Chase",DevComment="")
+GameplayTagList=(Tag="Test.StateTree.Event.Idle",DevComment="")
+GameplayTagList=(Tag="Test.StateTree.Event.Investigate",DevComment="")
+GameplayTagList=(Tag="Test.StateTree.Event.Patrol",DevComment="")

